version: "2.2"

services:
    app:
        container_name: app
        build: 
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/app
        environment: 
            - DB_HOST=${DB_HOST}
            - DB_NAME=${DB_NAME}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
            - PORT=${PORT}
        ports: 
            - "${PORT}:${PORT}"
        restart: unless-stopped
        depends_on:
            - redis
            - db

    db:
        container_name: db
        image: mongo
        volumes: 
            - .docker/data/db:/data/db
        restart: unless-stopped

    redis:
        container_name: redis
        image: redis:5-alpine
        volumes: 
            - .docker/data/redis:/data
        restart: unless-stopped
