version: "2"

services: 
    bareos:
        hostname: bareos
        container_name: bareos
        build: 
            context: ./Bareos
            dockerfile: Dockerfile
        volumes:
            - ./data/bareos-config:/etc/bareos
            - ./data/bareos-data:/var/lib/bareos
        ports: 
            - "8080:80"
            - "7722:22"
        restart: unless-stopped
        command: ["sleep","infinity"]

    bareos-client2:
        hostname: bareos-client2
        container_name: bareos-client2
        build: 
            context: ./Bareos-fd2
            dockerfile: Dockerfile
        volumes:
            - ./data/mysql-data:/var/lib/mysql
        ports:
            - "7822:22"
        restart: unless-stopped
        command: ["sleep","infinity"]