version: "2"

services: 
    bareos:
        hostname: bareos
        container_name: bareos
        image: bareos:v1
        volumes:
            - ./data/bareos-config:/etc/bareos
            - ./data/bareos-data:/var/lib/bareos
        ports: 
            - "8080:80"
            - "7722:22"
        restart: unless-stopped
        command: ["sleep","infinity"]

    mysql:
        hostname: mysql
        container_name: mysql-5.7
        image: ubuntu:18.04
        volumes:
            - ./data/mysql-data:/var/lib/mysql
        ports:
            - "3307:3306"
            - "7822:22"
        restart: unless-stopped
        command: ["sleep","infinity"]